name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Only deploy when pushing to main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test  # Run tests before deployment

  deploy:
    needs: test  # Only run if tests pass
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Vercel
        run: npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }}